id: P009190
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:27:16.839507
source_metadata:
  id: bdr:W3CN4709
  title: འདུལ་བ་མེ་ཏོག་ཕྲེང་རྒྱུད་ཀྱི་རྣམ་འགྲེལ་ཚིག་དོན་རབ་ཏུ་གསལ་བའི་ཉི་འོད།
  author: ''
  volumes:
    7ab8002de1c44494b4fb1521987a3c49:
      image_group_id: I3CN4711
      title: ''
      volume_number: 1
      total_pages: 552
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
