id: P009190
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4709
  title: འདུལ་བ་མེ་ཏོག་ཕྲེང་རྒྱུད་ཀྱི་རྣམ་འགྲེལ་ཚིག་དོན་རབ་ཏུ་གསལ་བའི་ཉི་འོད།
  author: ''
  volumes:
    7ab8002de1c44494b4fb1521987a3c49:
      image_group_id: I3CN4711
      title: ''
      volume_number: 1
      total_pages: 552
      base_file: v001.txt
