id: I54A433AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:33:12+00:00'
last_modified: '2022-06-08T09:15:40.047996+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4709
  title: འདུལ་བ་མེ་ཏོག་ཕྲེང་རྒྱུད་ཀྱི་རྣམ་འགྲེལ་ཚིག་དོན་རབ་ཏུ་གསལ་བའི་ཉི་འོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    285B:
      image_group_id: I3CN4711
      title: ''
      total_pages: 552
      order: 1
      base_file: 285B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
